# Generated by Django 6.0.1 on 2026-01-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_profile_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
