# Generated by Django 6.0.1 on 2026-01-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0002_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="type",
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Business.category",
            ),
        ),
    ]
