# Generated by Django 6.0.1 on 2026-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0003_remove_business_type_business_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="category",
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ManyToManyField(blank=True, to="Business.category"),
        ),
    ]
