# Generated by Django 6.0.1 on 2026-01-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0004_remove_business_category_business_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="category",
            new_name="categories",
        ),
    ]
