# Generated by Django 6.0.1 on 2026-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0005_rename_category_business_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", 5),
                    ("Very Good", 4),
                    ("Moderate", 3),
                    ("Not Satisfied", 2),
                    ("Awful", 1),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="business",
            name="status",
        ),
        migrations.AddField(
            model_name="business",
            name="approval_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Declined", "Declinedz"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
