# Generated by Django 6.0.1 on 2026-01-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0006_alter_review_review_rating_remove_business_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="imgage",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
