# Generated by Django 6.0.1 on 2026-01-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0007_business_imgage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "ordering": ["-vote_ratio", "-vote_total", "name"],
                "verbose_name_plural": "Businesses",
            },
        ),
        migrations.RenameField(
            model_name="business",
            old_name="imgage",
            new_name="image",
        ),
        migrations.AddField(
            model_name="business",
            name="vote_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="vote_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
