# Generated by Django 6.0.1 on 2026-01-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Business",
            "0008_alter_business_options_rename_imgage_business_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
