# Generated by Django 6.0.1 on 2026-01-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0009_business_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_rating",
            field=models.CharField(
                blank=True,
                choices=[("up", "Up Vote"), ("down", "Down Vote")],
                max_length=20,
                null=True,
            ),
        ),
    ]
