# Generated by Django 6.0.1 on 2026-01-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0010_alter_review_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="owner",
        ),
    ]
