# Generated by Django 6.0.1 on 2026-01-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0011_rename_user_review_owner"),
        ("Users", "0002_profile_is_admin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "business")},
        ),
    ]
