# Generated by Django 6.0.1 on 2026-01-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0013_alter_review_business"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
