# Generated by Django 6.0.1 on 2026-01-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0015_businessimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Business.address",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="approval_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Declined", "Declined"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
