# Generated by Django 6.0.1 on 2026-01-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Business",
            "0016_alter_business_address_alter_business_approval_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Business.address"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="approval_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Declined", "Declinedz"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
