# Generated by Django 6.0.1 on 2026-01-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Business",
            "0017_alter_business_address_alter_business_approval_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="approval_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Declined", "Declinedz"),
                ],
                default="Pending",
                max_length=10,
                null=True,
            ),
        ),
    ]
