# Generated by Django 6.0.1 on 2026-01-30 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0018_alter_business_approval_state"),
        ("Users", "0003_profile_bio_profile_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("message", models.CharField(max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("business_application", "Business Application"),
                            ("review_added", "Review Added"),
                            ("business_approved", "Business Approved"),
                            ("business_declined", "Business Declined"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="Users.profile",
                    ),
                ),
            ],
        ),
    ]
